-- ============================================================================
-- MyComplaintPortal — MySQL Database DDL Schema Script
-- Compatible with MySQL 5.7, 8.0, 8.4, MariaDB & Aiven MySQL Cloud
-- Relational Schemas for Users, Auth, Complaints, Departments, Admins, 
-- Element Collections, Timeline, Feedback & Live Analytics View
-- ============================================================================

CREATE DATABASE IF NOT EXISTS defaultdb;
USE defaultdb;

-- 1. AUTHENTICATION & USERS TABLE
CREATE TABLE IF NOT EXISTS USERS_AUTH (
    USER_ID VARCHAR(64) PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    PHONE VARCHAR(32),
    LOCATION VARCHAR(256),
    ROLE VARCHAR(32) NOT NULL DEFAULT 'CITIZEN',
    IS_BLOCKED TINYINT(1) NOT NULL DEFAULT 0,
    EMAIL_VERIFIED TINYINT(1) NOT NULL DEFAULT 0,
    PROFILE_IMAGE_URL VARCHAR(512),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. OTP VERIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS OTP_VERIFICATIONS (
    OTP_ID VARCHAR(64) PRIMARY KEY,
    EMAIL VARCHAR(128) NOT NULL,
    OTP_CODE VARCHAR(16) NOT NULL,
    EXPIRY_TIME DATETIME NOT NULL,
    IS_USED TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY IDX_OTP_EMAIL (EMAIL),
    KEY IDX_OTP_CODE (OTP_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS otp_verifications_seq (next_val BIGINT DEFAULT 1);
INSERT IGNORE INTO otp_verifications_seq VALUES (1);

-- 3. MUNICIPAL DEPARTMENTS TABLE
CREATE TABLE IF NOT EXISTS MUNICIPAL_DEPARTMENTS (
    DEPT_ID VARCHAR(64) PRIMARY KEY,
    DEPT_NAME VARCHAR(128) NOT NULL,
    DEPT_CODE VARCHAR(32) NOT NULL UNIQUE,
    OFFICIAL_EMAIL VARCHAR(128) NOT NULL,
    DESCRIPTION TEXT,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    TOTAL_COUNT INT DEFAULT 0,
    SOLVED_COUNT INT DEFAULT 0,
    PENDING_COUNT INT DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. ADMIN ACCOUNTS TABLE
CREATE TABLE IF NOT EXISTS ADMIN_ACCOUNTS (
    ADMIN_ID VARCHAR(64) PRIMARY KEY,
    USERNAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL UNIQUE,
    GRANT_LEVEL VARCHAR(64) NOT NULL DEFAULT 'Department Admin',
    DESIGNATION VARCHAR(128),
    BADGE_ID VARCHAR(64),
    DEPT_ID VARCHAR(64),
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ADMIN_DEPT FOREIGN KEY (DEPT_ID) REFERENCES MUNICIPAL_DEPARTMENTS(DEPT_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. COMPLAINTS MAIN TABLE
CREATE TABLE IF NOT EXISTS COMPLAINTS (
    COMPLAINT_ID VARCHAR(64) PRIMARY KEY,
    TITLE VARCHAR(256) NOT NULL,
    DESCRIPTION LONGTEXT NOT NULL,
    PINCODE VARCHAR(16) NOT NULL,
    LOCATION_NAME VARCHAR(256) NOT NULL,
    DEPT_ID VARCHAR(64),
    DEPT_NAME VARCHAR(128),
    OFFICER_EMAIL VARCHAR(128),
    STATUS VARCHAR(32) NOT NULL DEFAULT 'REGISTERED',
    UPVOTES INT NOT NULL DEFAULT 0,
    REPOSTS INT NOT NULL DEFAULT 0,
    IS_REPORTED TINYINT(1) NOT NULL DEFAULT 0,
    REPORT_COUNT INT DEFAULT 0,
    USER_ID VARCHAR(64) NOT NULL,
    USER_NAME VARCHAR(128) NOT NULL,
    USER_EMAIL VARCHAR(128),
    TRACKING_TOKEN VARCHAR(128) UNIQUE,
    PROOF_IMAGE_ID VARCHAR(128),
    OFFICER_NOTES LONGTEXT,
    WAS_REDIRECTED TINYINT(1) DEFAULT 0,
    REDIRECTED_FROM_DEPT VARCHAR(128),
    FEEDBACK_RATING INT,
    FEEDBACK_COMMENT TEXT,
    FEEDBACK_DATE DATETIME,
    AI_MATCHED_GRIEVANCE_ID VARCHAR(64),
    AI_MATCH_TYPE VARCHAR(64),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RESOLVED_AT DATETIME,
    KEY IDX_CMP_STATUS (STATUS),
    KEY IDX_CMP_PINCODE (PINCODE),
    KEY IDX_CMP_USER_ID (USER_ID),
    KEY IDX_CMP_DEPT_ID (DEPT_ID),
    KEY IDX_CMP_CREATED_AT (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. COMPLAINT ATTACHMENTS (GRIDFS EVIDENCE METADATA)
CREATE TABLE IF NOT EXISTS COMPLAINT_ATTACHMENTS (
    COMPLAINT_ID VARCHAR(64) NOT NULL,
    GRIDFS_IMAGE_ID VARCHAR(128) NOT NULL,
    KEY IDX_ATT_COMPLAINT (COMPLAINT_ID),
    CONSTRAINT FK_ATT_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. COMPLAINT UPVOTES TABLE
CREATE TABLE IF NOT EXISTS COMPLAINT_UPVOTES (
    COMPLAINT_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    PRIMARY KEY (COMPLAINT_ID, USER_ID),
    CONSTRAINT FK_UPVOTE_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. COMPLAINT REPOSTS TABLE
CREATE TABLE IF NOT EXISTS COMPLAINT_REPOSTS (
    COMPLAINT_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    PRIMARY KEY (COMPLAINT_ID, USER_ID),
    CONSTRAINT FK_REPOST_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. COMPLAINT REPORTS TABLE
CREATE TABLE IF NOT EXISTS COMPLAINT_REPORTS (
    COMPLAINT_ID VARCHAR(64) NOT NULL,
    USER_ID VARCHAR(64) NOT NULL,
    PRIMARY KEY (COMPLAINT_ID, USER_ID),
    CONSTRAINT FK_REPORT_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 10. COMPLAINT TIMELINE LOGS TABLE
CREATE TABLE IF NOT EXISTS COMPLAINT_TIMELINE (
    TIMELINE_ID VARCHAR(64) PRIMARY KEY,
    COMPLAINT_ID VARCHAR(64) NOT NULL,
    STAGE_TITLE VARCHAR(128) NOT NULL,
    STAGE_DATE VARCHAR(64) NOT NULL,
    STATUS_FLAG VARCHAR(32) NOT NULL,
    CONSTRAINT FK_TIMELINE_COMPLAINT FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. LIVE ANALYTICS VIEW FOR ADMIN DASHBOARD
CREATE OR REPLACE VIEW VW_COMPLAINT_STATS AS
SELECT 
    COUNT(*) AS TOTAL_SUBMITTED,
    SUM(CASE WHEN STATUS = 'RESOLVED' THEN 1 ELSE 0 END) AS TOTAL_RESOLVED,
    SUM(CASE WHEN STATUS = 'REGISTERED' THEN 1 ELSE 0 END) AS TOTAL_REGISTERED,
    SUM(CASE WHEN STATUS = 'VISITED' THEN 1 ELSE 0 END) AS TOTAL_VISITED,
    SUM(CASE WHEN STATUS = 'ACTION_IN_PROGRESS' THEN 1 ELSE 0 END) AS TOTAL_IN_PROGRESS,
    SUM(CASE WHEN WAS_REDIRECTED = 1 THEN 1 ELSE 0 END) AS TOTAL_REDIRECTED,
    COALESCE(SUM(REPOSTS), 0) AS TOTAL_REPOSTS
FROM COMPLAINTS;

-- ============================================================================
-- INITIAL SEED DATA FOR MYSQL DATABASE
-- ============================================================================

-- Seed Super Admin Account
INSERT IGNORE INTO USERS_AUTH (USER_ID, NAME, EMAIL, PASSWORD_HASH, ROLE, IS_BLOCKED, EMAIL_VERIFIED)
VALUES (
    'usr-superadmin', 
    'Super Admin Jai Surya', 
    'jaisurya7482@gmail.com', 
    '$2a$10$e8wFvV4qj4U74N5gPZ8j/uL2bE2iZ9eZ6bY7bX6v8b9c0d1e2f3g4',
    'SUPER_ADMIN', 
    0, 
    1
);

-- Seed Municipal Departments
INSERT IGNORE INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-pwd', 'Public Works Department (PWD)', 'DEPT-01', 'b.karthikeyan10000@gmail.com', 'Road maintenance, bridges, drainage and civic infrastructure.', 420, 378, 42);

INSERT IGNORE INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-eb', 'Electricity Board (EB)', 'DEPT-02', 'b.karthikeyan10000@gmail.com', 'Streetlight outages, transformer repairs, power grid management.', 380, 357, 23);

INSERT IGNORE INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-sanitation', 'Sanitation & Solid Waste Dept', 'DEPT-03', 'b.karthikeyan10000@gmail.com', 'Garbage collection, waste dumping, public hygiene.', 510, 464, 46);

INSERT IGNORE INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-water', 'Water Supply & Sewage Board', 'DEPT-04', 'jaisurya7482@gmail.com', 'Pipeline leaks, sewage overflow, drinking water supply.', 290, 249, 41);

INSERT IGNORE INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-transport', 'Transport & Traffic Division', 'DEPT-05', 'jaisurya7482@gmail.com', 'Traffic signals, bus shelter repair, road safety signs.', 180, 158, 22);

INSERT IGNORE INTO MUNICIPAL_DEPARTMENTS (DEPT_ID, DEPT_NAME, DEPT_CODE, OFFICIAL_EMAIL, DESCRIPTION, TOTAL_COUNT, SOLVED_COUNT, PENDING_COUNT)
VALUES ('dept-it', 'IT & Smart Governance Services', 'DEPT-06', 'jaisurya7482@gmail.com', 'Digital portal services, CCTV monitoring, smart city tech.', 120, 115, 5);
